### ISSUE TITLE
R Function for pulling all data from h5

### ISSUE THREAD

**Issue by jabard89** [riboviz/riboviz#181]
Hello,
Thanks again for your great work! A feature that I was looking for when using riboviz was an R function to load all of the reads in an h5 file into a dataframe. In particular, I wanted to trim reads from the beginning and end of the ORF because there was a buildup of ribosomes at the start codon that I thought were not actively translating. I also wanted to look at read length distribution at particular codons etc. I wrote my own function for doing this, but it took me a while (mostly learning how to interact with the h5 file), and it seems like something that might be broadly useful to other users.
Best,
Jared

**Comment by ewallace** [comment]
We have added a number of functions to get specific data items out of the h5 file, in the `rscripts/read_count_functions.R` file:

* GetGeneDatamatrix
* GetGeneReadLength
* GetGeneDatamatrix5start
* GetGeneDatamatrix3end
* TidyDatamatrix - turn those data matrices into tidy data frames.

These functions still need tests and documentation.

@jabard89 , do these functions address your needs, or do we need to add something?

Related to #61, as the script `bam_to_h5.R` gets data in to the h5 file, so that could be attacked simultaneously with functions to get data out of it.

**Comment by jabard89** [comment]
Those are great! I tested GetGeneDatamatrix %>% TidyDatamatrix and it does exactly what I expected. Haven't played with the other ones yet. Thanks!

**Comment by ewallace** [comment]
Closing as resolved; writing documentation for these functions is part of #153.

Thank you @jabard89 for your help!
