### ISSUE TITLE
"/usr/bin/env python" points to Python 2.7 when not using conda environment

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#204]
Hi everyone, I ran riboviz while not using a conda environment and ran into the issue that "/usr/bin/env python" points to Python 2.7 on my system. It might be worth noting this in the troubleshooting guide and/or highlighting this as a potential problem when running riboviz outside of a conda environment.

**Comment by mikej888** [comment]
Thanks. Please could you provide an example of the command you ran that caused this issue. As the docs recommend running the Python scripts using `python -m riboviz.tools.<TOOL>` then the shebangs won't be used, so I can't see how your issue arises.

Our docs need to be updated to say that users may need to run `python3 ...` if not using conda or similar.

Similarly, the shebangs in the RiboViz Python scripts can be updated to `#!/usr/bin/env python3`. If the user only has Python 2, this will fail, as desired. If they have `python3` then all should be well. Within a Python 3 conda environment, both `python` and `python` are available - `python` is symlinked to `python3` and that in turn to the current version of Python e.g.

```console
$ ls -l /home/ubuntu/miniconda3/envs/riboviz/bin/python
lrwxrwxrwx 1 ubuntu ubuntu 9 Jul  8 04:32 /home/ubuntu/miniconda3/envs/riboviz/bin/python -> python3.7
$ ls -l /home/ubuntu/miniconda3/envs/riboviz/bin/python3
lrwxrwxrwx 1 ubuntu ubuntu 9 Jul  8 04:32 /home/ubuntu/miniconda3/envs/riboviz/bin/python3 -> python3.7
```

**Comment by acope3** [comment]
Yes, I found this issue to be strange because the command I used was `python3.6 -m riboviz.tools.prep_riboviz -c vignette/vignette_config.yaml`. I'm attaching the 04_trim_5p_mismatch.log file, which is where riboViz breaks if I'm running outside of conda. This log file seems to indicate it's trying to run Python 2.7 and breaking because pysam is not installed for 2.7 on my machine. 
[04_trim_5p_mismatch.log](https://github.com/riboviz/riboviz/files/5048558/04_trim_5p_mismatch.log)

**Comment by mikej888** [comment]
Thanks. I see what is happening now. `python3.6 -m riboviz.tools.prep_riboviz` invokes the workflow using Python 3.6. The workflow in turn then invokes both the Python and R scripts implementing the steps of the workflow and, for Python, these use `python` by default.

I explored some options. I tried using `alias python3=python` but this does not work for sub-processes invoked via Python `subprocess.call` as the alias is not redefined for the subprocess.

https://stackoverflow.com/questions/41986507/unable-to-set-default-python-version-to-python3-in-ubuntu had a suggestion, using local symlinks.

```console
$ mkdir ~/bin
$ cd ~/bin
$ ln -s $(which python3) python
$ ln -s $(which pip3) pip
$ cd
```

I don't have an environment where I have RiboViz set up with Python 2 and Python 3 interpreters but I tried a simple example on a system which has both Python 2 and Python 3 and this seemed to overcome the `subprocess.call` issue above:

* Before defining the symlinks:

```console
$ python
Python 2.7.5 (default, Apr  1 2020, 10:09:19)
>>> import subprocess
>>> subprocess.call(["python", "--version"])
Python 2.7.5
0
>>> exit()
```
* Define the symlinks:
```console
$ mkdir ~/bin
$ cd ~/bin
$ ln -s $(which python3) python
$ ln -s $(which pip3) pip
$ cd
```
* Now:
```console
$ python
Python 2.7.5 (default, Apr  1 2020, 10:09:19)
>>> import subprocess
>>> subprocess.call(["python", "--version"])
Python 3.6.8
0
```

If the symlinks aren't picked up then you may need to add `~/bin` to your `PATH`:

```console
$ export PATH=~/bin:$PATH
```

Please give this a go and let me know how you get on.

Alternatively, would it be possible for you to use a conda or another virtual environment (e.g. virtualenv) rather than centrally-installed packages?

Notes on other options, requiring some redevelopment:

* Python workflow, edit all `python` occurrences in riboviz/workflow.py, to get Python interpreter to use from environment variable. This fix may or may not be applied (to be discussed) as the Python workflow, `riboviz.tools.prep_riboviz` is now deprecated (and will be removed in a future release).
* Nextflow workflow,  edit all `python` occurrences in prep_riboviz.nf, to get Python interpreter to use from environment variable.

**Comment by kavousan** [comment]
@acope3: can you please test the workaround outside conda and let us know?

**Comment by mikej888** [comment]
Once Alex has tried this, the documentation can be updated to provide this as Troubleshooting, with a strong recommendation that users use conda-type environment.

**Comment by acope3** [comment]
The symlink solution suggested by @mikej888 resolves this issue.

**Comment by mikej888** [comment]
@acope3 thanks for confirming :-)

**Comment by mikej888** [comment]
Added [python and python3](https://github.com/riboviz/riboviz/blob/develop/docs/user/install.md#python-and-python3) section to docs/user/install.md in "develop" branch.
