### ISSUE TITLE
Nextflow expects `pos_sp_nt_freq.tsv` when `do_pos_sp_nt_freq` is false

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#215]
As described in example-datasets/#4 : https://github.com/riboviz/example-datasets/issues/4#issuecomment-696723426

Cryptococcus dataset JEC21 not running via nextflow on Eddie, as it's giving an error relating to expected pos_sp_nt_freq.tsv file being missing.  

If do_pos_sp_nt_freq is FALSE, I don't think that should be expected.

**Comment by ewallace** [comment]
For our purposes, this is mostly a problem because it prevents nextflow continuing to the next step of the pipeline and executing `collateTpms`

**Comment by mikej888** [comment]
@FlicAnderson  wrote...

I finally got one of my jobs to complete on Eddie, but it's failed and I'm having trouble locating which part exactly is responsible for the failure. 

It's the Cryptococcus JEC21 dataset, and so running fullsize data, and using system links to scratch and the input files etc. I don't think that those are anything to do with the failure, and seem to be working ok so far!

I think the problem lies possibly in the nextflow code? Potentially something around how it might be expecting an output file "pos_sp_nt_freq.tsv" despite the fact "do_pos_sp_nt_freq" is set to false in the .yaml?  The error does ping up in the generateStatsFigs process though, so I checked that first in case of any issues. 

For reference, the riboviz branch was a days-old-if-that develop. 

In the output for the job I got this: 
```
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [furious_mestorf] - revision: 62d3b58c5d
Validating configuration only
Validated configuration
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [clever_minsky] - revision: 62d3b58c5d
[21/dbc8a3] Submitted process > buildIndicesrRNA (JEC21_rRNA)
# ... lots of processes happening as usual...
[d9/ada46b] Submitted process > generateStatsFigs (JdAGO1)
[f0/646ed1] Submitted process > samViewSort (JEC21)
[d9/ada46b] NOTE: Missing output file(s) `pos_sp_nt_freq.tsv` expected by process `generateStatsFigs (JdAGO1)` -- Error is ignored
[d2/69c0a5] Submitted process > outputBams (JEC21)
[d9/2e5534] Submitted process > makeBedgraphs (JEC21)
[3b/0746af] Submitted process > bamToH5 (JEC21)
[35/6e194f] Submitted process > generateStatsFigs (JEC21)
[35/6e194f] NOTE: Missing output file(s) `pos_sp_nt_freq.tsv` expected by process `generateStatsFigs (JEC21)` -- Error is ignored
No sample was processed successfully
```
I figured that this means that generate_stats_figs.R might have failed, but checking out the .command.log file for the generateStatsFigs (JEC21) 35/6e194f process as an example, it seems to have run as normal and completed: 
```
[1] "Created by: RiboViz"
[1] "Date: 2020-09-20 11:29:48"
[1] "File: /exports/eddie3_homes_local/fanders6/riboviz/riboviz/rscripts/generate_stats_figs.R"
[1] "Version: commit 9e41fb6854d93799edc037c7190429aa574dd0a1 date 2020-09-16 09:40:36 GMT"
[1] "generate_stats_figs.R running with parameters:"
$output_dir
[1] "."

$orf_fasta_file
[1] "JEC21_10p_up12dwn9_CDS_with_120bputrs.fa"

$orf_gff_file
[1] "JEC21_10p_up12dwn9_CDS_120bpL_120bpR.gff3"

$num_processes
[1] 32

$min_read_length
[1] 10

$max_read_length
[1] 50

$buffer
[1] 30

$primary_id
[1] "Name"

$dataset
[1] "Wallace_2020_JEC21"

$rpf
[1] TRUE

$features_file
[1] NA

$do_pos_sp_nt_freq
[1] FALSE

$t_rna_file
[1] NA

$codon_positions_file
[1] NA

$count_threshold
[1] 1

$length_threshold
[1] 500

$output_prefix
[1] ""

$hd_file
[1] "JEC21.h5"

$nnt_buffer
[1] 25

$nnt_gene
[1] 50

$asite_disp_length_file
[1] NA

$help
[1] FALSE

[1] "Starting: Check for 3nt periodicity globally"
`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
Saving 7 x 7 in image
[1] "Starting: Check for 3nt periodicity globally"
`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
Saving 7 x 7 in image
[1] "Completed: Check for 3nt periodicity globally"
Warning message:
In write.table(three_nucleotide_periodicity_data, file = tsv_file_path,  :
  appending column names to file
[1] "Starting: Distribution of lengths of all mapped reads"
Saving 7 x 7 in image
[1]Warning message:
In write.table(read_length_data, file = tsv_file_path, append = T,  : "Completed: Distribution of lengths of all mapped reads"
[1] "NOT calculating position-specific nucleotide frequency - reason: do_pos_sp_nt_freq parameter set to FALSE"
[1] "NOT checking for 3nt periodicity (frame) by gene - reason: asite_disp_length_file parameter not provided"
[1] "Starting: Position specific distribution of reads"
  appending column names to file
Saving 7 x 7 in image
Warning message:
In write.table(pos_sp_rpf_norm_reads_data, file = tsv_file_path,  :
  appending column names to file
[1] "Completed: Position specific distribution of reads - RPF method"
[1] "Completed: Position specific distribution of reads"
[1] "Starting: Calculate TPMs of genes"
[1]Warning message:
In write.table(tpms, file = tsv_file_path, append = T, sep = "\t",  :
  appending column names to file
 "Completed: Calculate TPMs of genes"
[1] "Skipped: Correlations between TPMs of genes with their sequence-based features - features_file.tsv not provided"
[1] "Skipped: Codon-specific ribosome densities for correlations with tRNAs - t-rna-file and/or codon-positions-file not provided"
[1] "Completed generate_stats_figs.R"
```
The .exitcode file contains a 0, which means that there wasn't an issue, I think? 

.command.err for that process contained just the usual warning message lines about write.table and so on, nothing unusual. 

Is there something in the nextflow code that perhaps expects `pos_sp_nt_freq.tsv` file to be created, even though this shouldn't be an expected output if do_pos_sp_nt_freq is set to FALSE?  I was trying to unpick what's going on in process generateStatsFigs in prep_riboviz.nf but I'm still not quite sure. 

Should the line in prep_riboviz.nf  process generateStatsFigs output:  
```
tuple val(sample_id), file("pos_sp_nt_freq.tsv") \ into pos_sp_nt_freq_tsv
```
instead be something like: 
```
tuple val(sample_id), file("pos_sp_nt_freq.tsv") \ optional (! do_pos_sp_nt_freq) \ into pos_sp_nt_freq_tsv
```
?  And if that's something along the right lines, are there any other edits that would need to be made?

**Comment by FlicAnderson** [comment]
@mikej888  thanks for adding my problem notes!  Hope they make sense so far?

**Comment by mikej888** [comment]
@FlicAnderson, Almost spot on with your fix :-) The fix is:

```
         tuple val(sample_id), file("pos_sp_nt_freq.tsv") \
           optional (! params.do_pos_sp_nt_freq) \
           into pos_sp_nt_freq_tsv
```

The `params.` prefix is required because the flag comes straight from the YAML file. The other optional outputs are based on variables created within `prep_riboviz.nf` itself.

**Comment by mikej888** [comment]
I've commited the fix to `develop`.

**Comment by mikej888** [comment]
The same pattern applies for any other optional outputs from any processes. If an output is not marked as optional then Nextflow checks that the file exists after its command (in this case generate_stats_figs.R) completes and will fail (even if the command itself succeeded).

**Comment by FlicAnderson** [comment]
*shakes fist at sky* SO CLOSE!!! :grin: 

Thanks, I'll give the fix a bash.  

Your `params.` explanation makes total sense, cheers :+1:

**Comment by FlicAnderson** [comment]
Currently testing this fix in latest run with Cryptococcus datasets, will update if/when it works & can close since it's merged to develop already.

**Comment by FlicAnderson** [comment]
Closing this since it's working with the Cryptococcus datasets and already merged.
