### ISSUE TITLE
Explore way to make recording and installation of R dependencies easier

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#292]
Options:

* renv, https://github.com/rstudio/renv and https://rstudio.github.io/renv/articles/renv.html
* DESCRIPTION file, https://r-pkgs.org/description.html

This may require creating an R package for our R components which may, in turn, motivate splitting our repository into Python, R and Nextflow repositories (see #52).

**Comment by FlicAnderson** [comment]
I think this issue may well be relevant/duplicate if we go down the {renv} route: #165 

Also I think that there'd be a lot of benefit of spitting the R code out into a R Package as per #52 because that way we get a lot of extra goodness in terms of testing structure and documentation structure for the R code.

**Comment by mikej888** [comment]
@FlicAnderson Sorry, I should've checked whether we had a current issue covering this (i.e. #165!)

**Comment by ewallace** [comment]
This issue has been superseded by making an R package #322. I am closing this issue and removing the R2.2 label.

Making an R package is a priority for future development.
