### ISSUE TITLE
Is dir_tmp obsolete due to nextflow work-dir?

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#324]
The temporary output directory `dir_tmp` was originally introduced (by me) as a way to store all the intermediate files in the analysis so that they were easy to store, find, and then delete. It was essential both for the shell and python workflows. Now, however, nextflow's `work_dir` achieves all those things. Doesn't that make `dir_tmp` obsolete, and it could be removed (as default) when we deprecate python workflow support #176 

However aren't we still using `dir_tmp` for regression tests?

OR could we have it optionally published only if `dir_tmp` is supplied in config file? If that's not too complicated?

Let's discuss.

**Comment by mikej888** [comment]
When Nextflow runs it prints each task and the hash allowing the user to find the `work` directory so that should be enough for users who want to look at the temporary files. How the `work` directory is structured, its contents and what are in these are already documented.

> However aren't we still using dir_tmp for regression tests?

`dir_tmp` is, optionally, used when running the regression tests (controlled by a `--check-index-tmp` flag passed to `pytest`) but this is most likely redundant. I'd hope that any issues with temporary files would either have caused the workflow to fail downstream before completion, or result in issues with the output files that would be caught when validating those output files.

> OR could we have it optionally published only if dir_tmp is supplied in config file? If that's not too complicated?

The Nextflow workflow already supports a `publish_index_tmp` flag (default `FALSE`). If `TRUE` files are copied from `work` to `dir_tmp` when a task completes. If `FALSE` symbolic links are created in `dir_tmp` to those in `work`.

I'd support removing `dir_tmp`. It would make both configuration and the workflow itself slightly simpler but may also make it simpler for users than having to explain the concept of both `work` directory and temporary directory to them.

**Comment by mikej888** [comment]
Relates to #176. If removing `dir_tmp` then this also needs to be added as one of the unused parameters to be removed by `riboviz.tools.upgrade_config` (extending the feature developed in #313).

**Comment by mikej888** [comment]
We agreed it is obsolete.

**Comment by ewallace** [comment]
Documentation could be clarified. My verbose suggestion.

`dir_tmp` provides easier access to intermediate files in the workflow that can be used for troubleshooting. By default, `publish_index_tmp` is `false` and the directory `dir_tmp` just provides symbolic links with helpful names. These symlinks point to files that are automatically logged by nextflow in the `work/` directory, which have automatically-generate cryptic directory names. If `publish_index_tmp` is `true`, then complete file copies are made, which can take up many gigabytes of space. This is not recommended in general.

Maybe a shorter version of that could go in the table in `riboviz/docs/user/prep-riboviz-config.md`?

**Comment by mikej888** [comment]
Commit 0d39c7c updates `prep-riboviz-config.md` and `prep-riboviz-operation.md` to clarify `publish_index_tmp` and caution against setting it to `true`.

**Comment by mikej888** [comment]
Discussed at 15/12/21 meeting. dir_tmp will not be removed as it, by default, only contains symbolic links.
