### ISSUE TITLE
Refactor prep_riboviz.py

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#34]
Refactor `__main__` method into:

* A new function which runs the workflow commands and raises exceptions for any issues.
* A `__main__` function which invokes the above and maps exceptions to exit codes.

**Comment by mikej888** [comment]
Closed by 6e1b443 and #65.

**Comment by mikej888** [comment]
@FlicAnderson to confirm that work on #29 has used the refactored prep_riboviz.py in "develop" branch. Once confirmed that this has been done, this issue can be moved to Done.

**Comment by FlicAnderson** [comment]
Original Guydosh-Green 2014 non-downsampled version of vignette ran successfully on develop branch latest commits (at that time, end of Aug) and I haven't yet re-run with refactored code. 

Muzzey 2014 Candida albicans dataset: this ran (09th Sept) on latest develop branch refactored prep_riboviz (latest commit was b8746659) but all samples failed after bam-to-h5.R due to bug #66 where features_file=NULL isn't handled correctly in generate_stats_fig.R for organisms where we don't have this file. 

Subsequent datasets will continue to use refactored prep_riboviz.py and latest develop branch, after regression tests have been run successfully.

Issue can be moved to done.
