### ISSUE TITLE
Can't download R 3.6, or later

### ISSUE THREAD

**Issue by Joseph-Waldron** [riboviz/riboviz#387]
When I run the following

$ sudo apt install -y r-base
$ sudo apt install -y r-base-dev

it installs 3.4.4 but I need version 3.6 or above.

I have tried the following lines in the instructions but after running

$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9

gpg: keyserver receive failed: Connection timed out

**Comment by mikej888** [comment]
I retried the command on my Ubuntu VM and it worked fine:
```console
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```
I also tried the alternative command you tried also and it too worked fine:
```console
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```
I found another link, https://unix.stackexchange.com/questions/361213/unable-to-add-gpg-key-with-apt-key-behind-a-proxy, which also offers suggestions. Based on those,

Try using http://keyserver.ubuntu.com instead of keyserver.ubuntu.com

Try
```console
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --keyserver-options http-proxy=<YOUR_HTTP_PROXY_URL> --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```
e.g.
```console
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --keyserver-options http-proxy=http://localhost:1234 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```
replacing `localhost:1234` with whatever your HTTP proxy URL is.

Try manually downloading the key file:

* Access the key file directly, by visiting https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE298A3A825C0D65DFD57CBB651716619E084DAB9
* Copy and paste the entire contents of the page into a plain-text file e.g. `r-key.gpg`.
* Add the key:

```console
$ sudo apt-key add r-key.gpg
OK
```

* Check:
```
$ sudo apt-key list
/etc/apt/trusted.gpg
--------------------
...
pub   rsa2048 2010-10-19 [SCA] [expires: 2027-09-30]
      E298 A3A8 25C0 D65D FD57  CBB6 5171 6619 E084 DAB9
uid           [ unknown] Michael Rutter <marutter@gmail.com>
sub   rsa2048 2010-10-19 [E] [expires: 2027-09-30]
```

**Comment by Joseph-Waldron** [comment]
Thanks Mike, manually adding the HTTP proxy URL seems to have worked. Thanks again

**Comment by mikej888** [comment]
@Joseph-Waldron glad it worked, thanks for letting me know.
