### ISSUE TITLE
Document how downloading results and moving them around may affect the shiny visualizations

### ISSUE THREAD

**Issue by kavousan** [riboviz/riboviz#430]
Spin-out of #410.

**Comment by FlicAnderson** [comment]
Could we advise people to try viewing using port forwarding a la #431 rather than moving their viz around?  

#431 isn't an exact replicate of the issue of moving files affecting the viz (#410) or a proper 'fix' for that, because we still haven't documented how moving the files around affects the visualization, but at least it's an alternative which we're documenting which might solve the reason why people are moving things around and causing instability?

**Comment by john-s-f** [comment]
That seems like a partial solution. The port forwarding issue is one where the visualization tool simply wouldn't work from a headless machine unless you can get it on the right port. The ability to view your results on a server using port forwarding _could_ prevent people from needing to download their results but they may consider it a bother to have to constantly log on to a remote machine in order to view their results.
